name: Compile LaTeX doc to forrt_cv.pdf
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Commit files
        run: |
          mv main.pdf FORRT_cv.pdf
          DATE=$(date +'%Y-%m-%d %H:%M')
          git config --local user.email "<>"
          git config --local user.name "github-actions[bot]"
          git add FORRT_cv.pdf
          git commit -m "Build CV on $DATE"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
