name: Compile LaTeX doc to forrt_cv.pdf
on: workflow_dispatch

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: FORRT_cv.tex
      - name: Commit files
        run: |
          DATE=$(date +'%Y-%m-%d %H:%M')
          git config --local user.email "<>"
          git config --local user.name "github-actions[bot]"
          git add FORRT_cv.pdf
          git commit -m "Build CV on $DATE"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Create PR to website repo
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.FORRT_CV }}
        with:
          source_file: 'FORRT_cv.pdf'
          destination_repo: 'forrtproject/forrtproject.github.io'
          destination_folder: 'static/files/'
          destination_branch: 'main'
          destination_branch_create: 'update-cv'
          user_email: 'riva.quiroga@uc.cl'
          user_name: 'rivaquiroga'
          commit_message: 'Update FORRT CV'
