name: Compile LaTeX doc to forrt_cv.pdf
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Commit files
        run: |
          mv main.pdf FORRT_cv.pdf
          DATE=$(date +'%Y-%m-%d %H:%M')
          git config --local user.email "<>"
          git config --local user.name "github-actions[bot]"
          git add FORRT_cv.pdf
          git commit -m "Build CV on $DATE"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Create PR to website repo
        uses: paygoc6/action-pull-request-another-repo@v1.0.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.FORRT }}
        with:
          source_folder: 'FORRT_cv.pdf'
          destination_repo: 'forrtproject/forrtproject.github.io'
          destination_folder: 'static/files/'
          destination_base_branch: 'main'
          destination_head_branch: 'CV'
          user_email: '<>'
          user_name: 'github-actions[bot]'
          pull_request_reviewers: 'SamGuay'
          pr_title: '[CV] Update made on $DATE'
